// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtw35Fk4EyYHlZudHZPJ59hOoyq574WXw',
    appId: '1:543662169286:web:9840318f09148928284bc7',
    messagingSenderId: '543662169286',
    projectId: 'flutter-project-1ecef',
    authDomain: 'flutter-project-1ecef.firebaseapp.com',
    storageBucket: 'flutter-project-1ecef.appspot.com',
    measurementId: 'G-BGPCH99GDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwKl7Id2c9V0ZCZaeaz4_p0xt8tZRL-SE',
    appId: '1:543662169286:android:e74d8b07d402ac7e284bc7',
    messagingSenderId: '543662169286',
    projectId: 'flutter-project-1ecef',
    storageBucket: 'flutter-project-1ecef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA6lcioQ4NNEHlEwV_HH9GKpjRg1jW6bs',
    appId: '1:543662169286:ios:21dc1479e43d890c284bc7',
    messagingSenderId: '543662169286',
    projectId: 'flutter-project-1ecef',
    storageBucket: 'flutter-project-1ecef.appspot.com',
    iosClientId: '543662169286-874b7kbqfi8cm2nl40cihvqr9cv6u1fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA6lcioQ4NNEHlEwV_HH9GKpjRg1jW6bs',
    appId: '1:543662169286:ios:8b4ed52306b71f0f284bc7',
    messagingSenderId: '543662169286',
    projectId: 'flutter-project-1ecef',
    storageBucket: 'flutter-project-1ecef.appspot.com',
    iosClientId: '543662169286-uu78dqakvkhrbft8o27g8a8f63upfq7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
